.gitignore

- pycache 삭제를 위한 gitignore 수정
<br/>

fix: gitignore 수정

---

Main.py

- 메인함수에서 auth 서비스 띄우는 함수 하나만 추가했습니다. 브랜치가 나뉘어서 두 개 pr로 올립니다. 
<br/>

메인함수에서 auth서비스 띄우기

---

Main.py
auth/Auth.py

- 회원가입 비밀번호 인식 불가 에러 해결
- 회원가입 완료 시 data/user.txt 생성 기능 구현
<br/>

fix(Auth.py): Auth.py 오류 해결

---

movie/MovieInfo.py

fix: 평점 float 형으로 수정

---

auth/Auth.py

- 로그인 이후 프롬프트가 출력되지 않는 에러를 해결했습니다.
<br/>

fix(Auth.py): 로그인 이후 프롬프트 에러 해결

---

auth/Auth.py

fix(Auth.py): 프롬프트 중복 출력 에러 해결

---

home/Home.py
mypage/MyPage.py
search/Search.py

snake_case로 변경 및 임포트 경로 변경

---

search/Search.py

영화 검색에서 공백 문자를 무시하고 검색

---

search/Search.py

[영화 검색] 시 영화 제목과 감독명에 대해 동시 검색하도록 변경

---

home/Home.py

- Home 프롬프트를 기획서에 맞게 수정했습니다.
<br/>

fix(Home.py): Home 프롬프트 수정

---

home/Home.py
movie/MovieList.py

Home.py, MovieList.py 비정상 결과 출력 메세지 수정

---

movie/MovieList.py

영화 리스트 조회순 추가

---

Main.py
auth/Auth.py
home/Home.py

- auth와 home에서 관리하던 메인 로직을 main쪽으로 빼내어 수정했습니다.
<br/>
- [ x] 코드 리팩토링

main로직 가시화

---

movie/MovieInfo.py

rate_movie함수 코드 수정

---

movie/MovieInfo.py

rate_movie 오류 수정

---

mypage/MyPage.py
search/Search.py

찜 목록 및 영화 검색 결과에서 이제 감독명도 표시됨

---

Main.py
auth/Auth.py
home/Home.py
movie/MovieList.py
mypage/MyPage.py

- 선행 0 예외처리를 구현했습니다.
```
if user_selection != user_selection.lstrip('0') and user_selection != '0':
print("존재하지 않는 메뉴 번호입니다.")
continue
```
<br/>

feat(Auth, MovieList, Home, Mypage): 선행 0 예외 처리 구현

---

auth/Auth.py

- 프로그램 실행 후 0 입력 시 프롬프트 출력 오류 수정
<br/>

fix(Auth.py): 프로그램 실행 후 0 입력 시 프롬프트 출력 오류 수정

---

MovieDTO.py
movie/MovieInfo.py
movie/MovieList.py

장르 데이터 형식 저장 오류 수정

---

movie/MovieList.py

refactor: 평점 후 영화 리스트 반영

---

MovieDTO.py

MovieDTO.py의 update_movie_file 함수 리팩터링 및 수정

---

MovieDTO.py
movie/MovieInfo.py

- 평점이 중복되서 여러 개 추가되게 movie.txt와 MovieInfo,py 수정
<br/>

feat: 여러 평점 기능 추가

---

movie/MovieInfo.py

- 변경사항을 작성해주세요
check_movie 함수 추가
-> movie.txt 파일에 반영된 평가한 사용자 ID와 평점의 데이터를 받아와 영화 상세 정보에 표시해주는 함수
<br/>

check_movie 함수 추가

---

movie/MovieInfo.py

- 영화 상세 화면에서 평점남긴 유저들 확인 가능, 유저 아이디 입력시 해당 유저의 모든 평점과 평점 평균 확인 가능
<br/>

movieRatingInfo

---

movie/MovieInfo.py

- 교수님 요구사항 따라 여러 평점 계산 로직 개선, 평점 출력시 한 유저의 평점은 한 줄에 출력하도록 함
<br/>

요구사항 분석 및 출력 수정

---

MovieDTO.py
search/Search.py

감독 아이디 기반 검색 로직 완성 및 테스트 성공

---

movie/MovieInfo.py

Refactor: Simplified view_movie_ratings function for clarity

---

movie/MovieInfo.py

- 영화 상세페이지 > 평가인원 확인 로직에서 프롬프트 출력 수정
- 요구사항대로 평가는 같은 사람이라면 한번에 출력하도록 수정
<br/>

자잘한 프롬프트 출력 수정

---

movie/MovieInfo.py

fix(MovieInfo.py): Remove spaces from userInput
